# Generated by Django 4.0.4 on 2022-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='comment posting time'),
        ),
    ]
